name: pway
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - pip
  - Flask
  - Flask-Login==0.3.2
  - Flask-Bootstrap
  - Flask-SQLAlchemy
  - Flask-Security
  - Flask-Script
  - Flask-Uploads
  - Flask-Migrate
  - numpy
  - scipy
  - pymysql
  - Unidecode
  - cython
  - pandas
  - matplotlib
  - celery==3.1.25
  - bokeh==0.12.6
  - matplotlib
  - scikit-learn
  - pip:
    - py-bcrypt
    - flask_httpauth
    - mod_wsgi
    - python-dotenv
    - redis==2.10.6
    - flower