name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pip
  - Flask
  - alembic==1.7
  - Flask-Login==0.3.2
  - Flask-Bootstrap
  - Flask-SQLAlchemy
  - Flask-Security
  - Flask-Script
  # - Flask-Uploads
  - Flask-Migrate==2.7.0
  - numpy
  - scipy
  - pymysql
  - Unidecode
  - cython
  - pandas
  - matplotlib
  - celery==3.1.25
  - bokeh==0.12.6
  - matplotlib
  - scikit-learn
  - openpyxl
#  - gcc
  - pip:
#    - py-bcrypt
    - flask_httpauth
    # - mod_wsgi
    - python-dotenv
    - redis==2.10.6
#    - flower
    - email_validator
