name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pip
  - Flask
  - alembic
  - Flask-Login
  - Flask-Bootstrap
  - Flask-SQLAlchemy
  - flask-security-too>=5.3.1
  - flask-mail
  - Flask-Script
  - Flask-Migrate
  - numpy
  - scipy
  - pymysql
  - Unidecode
  - cython
  - pandas
  - celery
  - bokeh
  - matplotlib
  - scikit-learn
  - openpyxl
  - python-dotenv
  - email_validator
  - flask-httpauth
  - redis-py
  # dev extras
  - jupyterlab
#  - gcc
#  - pip:
#    - py-bcrypt
#    - mod_wsgi
#    - redis
#    - flower
