"""empty message

Revision ID: 09f0ee1a4dcc
Revises: b11d484b935d
Create Date: 2018-01-13 16:15:09.864457

"""

# revision identifiers, used by Alembic.
revision = '09f0ee1a4dcc'
down_revision = 'b11d484b935d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('is_demo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'is_demo')
    # ### end Alembic commands ###
