"""empty message

Revision ID: 19575e2bbee7
Revises: 09f0ee1a4dcc
Create Date: 2018-01-17 18:35:18.368568

"""

# revision identifiers, used by Alembic.
revision = '19575e2bbee7'
down_revision = '09f0ee1a4dcc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('n_patients_crop', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'n_patients_crop')
    # ### end Alembic commands ###
