"""empty message

Revision ID: 25016c5c4b0f
Revises: 3b92ecf22681
Create Date: 2015-08-07 15:55:38.077023

"""

# revision identifiers, used by Alembic.
revision = '25016c5c4b0f'
down_revision = '3b92ecf22681'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'run_accepted')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('run_accepted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    ### end Alembic commands ###
