"""empty message

Revision ID: 25d1f9e2928e
Revises: 4a4f183423f3
Create Date: 2016-04-07 14:25:11.388781

"""

# revision identifiers, used by Alembic.
revision = '25d1f9e2928e'
down_revision = '4a4f183423f3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bmr',
    sa.Column('bmr_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('tissue', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('rand_str', sa.String(length=255), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('n_rejected', sa.Integer(), nullable=True),
    sa.Column('n_ignored', sa.Integer(), nullable=True),
    sa.Column('n_loaded', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('bmr_id')
    )

    op.add_column('uploads', sa.Column('bmr_id', sa.Integer(), nullable=True))
    op.alter_column('uploads', 'is_queued',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.create_foreign_key(None, 'uploads', 'bmr', ['bmr_id'], ['bmr_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.alter_column('uploads', 'is_queued',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.drop_column('uploads', 'bmr_id')
    op.drop_table('bmr')
    ### end Alembic commands ###
