"""empty message

Revision ID: 2e13e634399e
Revises: None
Create Date: 2014-12-12 18:13:39.981120

"""

# revision identifiers, used by Alembic.
revision = '2e13e634399e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
