"""empty message

Revision ID: 3b92ecf22681
Revises: 3cb7bd044853
Create Date: 2015-08-03 11:30:03.522336

"""

# revision identifiers, used by Alembic.
revision = '3b92ecf22681'
down_revision = '3cb7bd044853'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    ### end Alembic commands ###
