"""empty message

Revision ID: 42ff7701dc87
Revises: 36d5d10ab490
Create Date: 2015-12-18 16:40:26.626950

"""

# revision identifiers, used by Alembic.
revision = '42ff7701dc87'
down_revision = '36d5d10ab490'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    ### end Alembic commands ###
