"""empty message

Revision ID: 463a674df1c8
Revises: 4b86726d8ef3
Create Date: 2015-04-08 11:17:26.795243

"""

# revision identifiers, used by Alembic.
revision = '463a674df1c8'
down_revision = '4b86726d8ef3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('algorithm', sa.String(length=255),
                                       nullable=True,
                                       server_default='gene_count'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'algorithm')
    ### end Alembic commands ###
