"""empty message

Revision ID: 4b86726d8ef3
Revises: 166547d0dc22
Create Date: 2014-12-17 09:58:43.727865

"""

# revision identifiers, used by Alembic.
revision = '4b86726d8ef3'
down_revision = '166547d0dc22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
