"""empty message

Revision ID: 54225938b150
Revises: 49ebff1263b0
Create Date: 2015-09-28 17:18:13.209102

"""

# revision identifiers, used by Alembic.
revision = '54225938b150'
down_revision = '49ebff1263b0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('n_ignored', sa.Integer(), nullable=True))
    op.add_column('uploads', sa.Column('n_rejected', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'n_rejected')
    op.drop_column('uploads', 'n_ignored')
    ### end Alembic commands ###
