"""empty message

Revision ID: 63a13ecafbd
Revises: 25d1f9e2928e
Create Date: 2016-04-14 16:19:16.672405

"""

# revision identifiers, used by Alembic.
revision = '63a13ecafbd'
down_revision = '25d1f9e2928e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('has_annot', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'has_annot')
    ### end Alembic commands ###
